"""Cron scheduler for vault skills."""

from __future__ import annotations

import time
import threading
import yaml
from pathlib import Path
from typing import Any
from datetime import datetime, timezone

import schedule
from rich.console import Console

from .registry import CapabilityRegistry
from .git_workflow import VaultGit
from .config import find_vault_root

console = Console()


class SkillScheduler:
    """Runs scheduled skills via cron-like expressions."""
    
    def __init__(self, vault_path: Path | None = None):
        self.vault_path = Path(vault_path) if vault_path else find_vault_root()
        self.cron_file = self.vault_path / ".vault" / "cron.yaml"
        self.registry = CapabilityRegistry(self.vault_path)
        self.git = VaultGit(self.vault_path)
        self.jobs: list[schedule.Job] = []
        self._running = False
        self._thread: threading.Thread | None = None
    
    def load(self) -> None:
        """Load cron jobs from config."""
        if not self.cron_file.exists():
            console.print("[yellow]No cron.yaml found. Create one with 'vault cron --edit'[/yellow]")
            return
        
        with open(self.cron_file) as f:
            config = yaml.safe_load(f) or {}
        
        # Clear existing jobs
        schedule.clear()
        self.jobs = []
        
        for job_config in config.get("jobs", []):
            if not job_config.get("enabled", True):
                continue
            self._schedule_job(job_config)
    
    def _schedule_job(self, config: dict) -> None:
        """Parse cron expression and schedule."""
        skill_id = config["skill"]
        cron = config["schedule"]
        
        skill = self.registry.get(skill_id)
        if not skill:
            console.print(f"[red]Skill '{skill_id}' not found[/red]")
            return
        
        # Parse simplified cron: "0 2 * * 0" = Sunday 2am
        parts = cron.split()
        if len(parts) != 5:
            console.print(f"[red]Invalid cron: {cron}[/red]")
            return
        
        minute, hour, day, month, weekday = parts
        
        job = None
        if weekday == "0" and day == "*" and month == "*":
            job = schedule.every().sunday.at(f"{hour.zfill(2)}:{minute.zfill(2)}")
        elif weekday == "*" and day == "*" and month == "*":
            job = schedule.every().day.at(f"{hour.zfill(2)}:{minute.zfill(2)}")
        elif weekday == "*" and month == "*":
            job = schedule.every().day.at(f"{hour.zfill(2)}:{minute.zfill(2)}")
        
        if job:
            job.do(self._execute_skill, skill_id, config)
            self.jobs.append(job)
            console.print(f"[green]Scheduled:[/green] {skill.name} @ {cron}")
    
    def _execute_skill(self, skill_id: str, config: dict) -> None:
        """Execute a skill and stage results."""
        console.print(f"[blue]Running scheduled skill:[/blue] {skill_id}")
        
        ok, msg = self.registry.validate(skill_id, "scheduler")
        if not ok:
            console.print(f"[red]Skip {skill_id}: {msg}[/red]")
            return
        
        skill = self.registry.get(skill_id)
        if not skill:
            return
        
        # Execute skill module
        try:
            result = self._run_skill_module(skill_id)
            
            # Stage to dev branch
            if skill.outputs:
                for output in skill.outputs:
                    if output.path_template:
                        path = Path(output.path_template)
                        content = yaml.dump(result, default_flow_style=False, sort_keys=False)
                        self.git.stage_write(path, content, agent="scheduler")
            
            # Raise PR
            pr = self.git.raise_pr(
                title=f"[bot] Scheduled: {skill.name}",
                description=f"Auto-generated by cron: {skill_id}\n\n{config.get('description', '')}",
            )
            console.print(f"[green]PR raised:[/green] {pr.pr_id}")
            
        except Exception as e:
            console.print(f"[red]Skill {skill_id} failed: {e}[/red]")
    
    def _run_skill_module(self, skill_id: str) -> dict[str, Any]:
        """Import and execute a skill module."""
        import importlib.util
        
        skill_path = self.vault_path / ".vault" / "skills" / f"{skill_id}.py"
        if not skill_path.exists():
            # Fallback: use built-in implementations
            return self._run_builtin(skill_id)
        
        spec = importlib.util.spec_from_file_location(skill_id, skill_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        if hasattr(module, "execute"):
            return module.execute()
        raise RuntimeError(f"Skill {skill_id} has no execute() function")
    
    def _run_builtin(self, skill_id: str) -> dict[str, Any]:
        """Run built-in skills without external modules."""
        if skill_id == "archive-stale":
            from .archive import ArchiveEngine
            engine = ArchiveEngine(self.vault_path)
            return engine.run()
        elif skill_id == "health-check":
            from .health import VaultHealth
            health = VaultHealth(self.vault_path)
            return health.check()
        elif skill_id == "stale-project-reminder":
            return self._stale_project_reminder()
        else:
            raise RuntimeError(f"No built-in implementation for {skill_id}")
    
    def _stale_project_reminder(self) -> dict[str, Any]:
        """Find projects inactive > 30 days."""
        from datetime import timedelta
        
        projects_dir = self.vault_path / "projects"
        if not projects_dir.exists():
            return {"stale_projects": []}
        
        threshold = timedelta(days=30)
        stale = []
        
        for file in projects_dir.rglob("*.md"):
            mtime = datetime.fromtimestamp(file.stat().st_mtime, tz=timezone.utc)
            if datetime.now(timezone.utc) - mtime > threshold:
                stale.append({
                    "project": file.stem,
                    "last_active": mtime.isoformat(),
                    "days_inactive": (datetime.now(timezone.utc) - mtime).days,
                })
        
        return {
            "stale_projects": stale,
            "count": len(stale),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }
    
    def start(self) -> None:
        """Start scheduler in background thread."""
        self.load()
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()
        console.print("[green]Scheduler started[/green]")
    
    def stop(self) -> None:
        """Stop scheduler."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        console.print("[yellow]Scheduler stopped[/yellow]")
    
    def _loop(self) -> None:
        """Blocking loop for scheduler thread."""
        while self._running:
            schedule.run_pending()
            time.sleep(60)
    
    def run_once(self, skill_id: str | None = None) -> None:
        """Run scheduled jobs immediately (for testing)."""
        if skill_id:
            skill = self.registry.get(skill_id)
            if skill and skill.schedule:
                self._execute_skill(skill_id, {"skill": skill_id, "schedule": skill.schedule})
        else:
            schedule.run_all()
    
    def status(self) -> dict[str, Any]:
        """Return scheduler status."""
        return {
            "running": self._running,
            "jobs_scheduled": len(self.jobs),
            "next_run": str(self.jobs[0].next_run) if self.jobs else None,
            "cron_file": str(self.cron_file),
        }
