#!/bin/bash
# Auto-generated by Vault Plumber
VAULT_ROOT="VAULT_ROOT_PLACEHOLDER"
COMMITS_DIR="$VAULT_ROOT/commits"
mkdir -p "$COMMITS_DIR"

HASH=$(git rev-parse --short HEAD)
MSG=$(git log -1 --pretty=%B | head -1)
AUTHOR=$(git log -1 --pretty=%an)
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
FILES=$(git diff-tree --no-commit-id --name-only -r HEAD | head -30 | sed 's/^/- /')
BRANCH=$(git rev-parse --abbrev-ref HEAD)
DATE_ONLY=$(date -u +%Y-%m-%d)

FILE="$COMMITS_DIR/$DATE_ONLY-$HASH.md"

if [ ! -f "$FILE" ]; then
cat > "$FILE" <<'INNER_EOF'
---
id: commit-HASH_PLACEHOLDER
created: DATE_PLACEHOLDER
source: git-hook
branch: BRANCH_PLACEHOLDER
author: AUTHOR_PLACEHOLDER
---

# Commits on DATE_ONLY_PLACEHOLDER

INNER_EOF
fi

cat >> "$FILE" <<'INNER_EOF'
- **[HASH_PLACEHOLDER]** MSG_PLACEHOLDER
  - Files: FILES_PLACEHOLDER
  - Branch: BRANCH_PLACEHOLDER

INNER_EOF
