#!/usr/bin/env python3
"""
Vault Plumber — Zero-Write Context Pipeline for Personal Vault

Install once per project. Captures your work automatically.

Usage:
    python vault-plumber.py --install /path/to/project
    python vault-plumber.py --status /path/to/project
    python vault-plumber.py --run-session-recorder /path/to/project
    python vault-plumber.py --generate-overview /path/to/workspace
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

VAULT_DIRS = ["projects", "meetings", "decisions", "sessions", "commits", "people"]

SCRIPT_DIR = Path(__file__).parent.resolve()
HOOK_TEMPLATE = SCRIPT_DIR / "hook-template.sh"


@dataclass
class SessionCapture:
    project: str
    timestamp: str
    files_touched: list
    git_stat: str
    commit_messages: list
    duration_hint: str = ""


def find_vault_root(project_path: Path):
    path = Path(project_path).resolve()
    if (path / ".vault" / "config.yaml").exists():
        return path
    if (path / "AGENTS.md").exists() and (path / ".vault").exists():
        return path
    return None


def init_vault(project_path: Path):
    vault_path = Path(project_path).resolve()
    vault_dir = vault_path / ".vault"
    vault_dir.mkdir(parents=True, exist_ok=True)

    for sub in ["skills", "registry", "staging", "archive", "index", "schemas"]:
        (vault_dir / sub).mkdir(exist_ok=True)

    for d in VAULT_DIRS:
        (vault_path / d).mkdir(exist_ok=True)

    config = {
        "version": "1.0",
        "auto_archive_days": 120,
        "directories": [
            {
                "name": d,
                "description": f"Auto-captured {d}",
                "path": str(vault_path / d),
                "vault_path": str(vault_path / d),
                "archive_after_days": 30 if d in ("sessions", "commits") else 120,
                "required_frontmatter": ["id", "created", "source"],
                "templates": [],
            }
            for d in VAULT_DIRS
        ],
    }
    try:
        import yaml
        with open(vault_dir / "config.yaml", "w") as fh:
            yaml.dump(config, fh, default_flow_style=False, sort_keys=False)
    except ImportError:
        lines = ["version: '1.0'", "auto_archive_days: 120", "directories:"]
        for d in config["directories"]:
            lines.append(f"  - name: {d['name']}")
            lines.append(f"    description: {d['description']}")
            lines.append(f"    path: {d['path']}")
            lines.append(f"    vault_path: {d['vault_path']}")
            lines.append(f"    archive_after_days: {d['archive_after_days']}")
            lines.append(f"    required_frontmatter: {d['required_frontmatter']}")
        with open(vault_dir / "config.yaml", "w") as fh:
            fh.write("\n".join(lines) + "\n")

    (vault_path / "AGENTS.md").write_text(
        "# Project Context\n\n"
        "All entries in this vault are auto-generated by Vault Plumber.\n"
        "Do not edit manually unless marked `source: manual`.\n"
    )

    gitignore = vault_path / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(".vault/staging/\n.vault/index/\n.DS_Store\n")

    return vault_path


def install_git_hook(project_path: Path):
    git_dir = project_path / ".git"
    if not git_dir.exists():
        print(f"[warn] No .git repo in {project_path}. Skipping hook.")
        return

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_path = hooks_dir / "post-commit"

    vault_root = str(project_path.resolve())

    if HOOK_TEMPLATE.exists():
        template = HOOK_TEMPLATE.read_text()
    else:
        print("[warn] hook-template.sh not found. Using minimal fallback.")
        template = (
            "#!/bin/bash\n"
            "VAULT_ROOT="" + vault_root + ""\n"
            "COMMITS_DIR="$VAULT_ROOT/commits"\n"
            "mkdir -p "$COMMITS_DIR"\n"
            "\n"
            "HASH=$(git rev-parse --short HEAD)\n"
            "MSG=$(git log -1 --pretty=%B | head -1)\n"
            "DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)\n"
            "DATE_ONLY=$(date -u +%Y-%m-%d)\n"
            "\n"
            "FILE="$COMMITS_DIR/$DATE_ONLY-$HASH.md"\n"
            "echo "---\nid: commit-$HASH\ncreated: $DATE\nsource: git-hook\n---\n" > "$FILE"\n"
            "echo "- [$HASH] $MSG" >> "$FILE"\n"
        )

    hook = template
    hook = hook.replace("VAULT_ROOT_PLACEHOLDER", vault_root)
    hook = hook.replace("HASH_PLACEHOLDER", "$HASH")
    hook = hook.replace("DATE_PLACEHOLDER", "$DATE")
    hook = hook.replace("BRANCH_PLACEHOLDER", "$BRANCH")
    hook = hook.replace("AUTHOR_PLACEHOLDER", "$AUTHOR")
    hook = hook.replace("DATE_ONLY_PLACEHOLDER", "$DATE_ONLY")
    hook = hook.replace("MSG_PLACEHOLDER", "$MSG")
    hook = hook.replace("FILES_PLACEHOLDER", "$(echo $FILES | tr '\\n' ', ')")

    hook_path.write_text(hook)
    hook_path.chmod(0o755)
    print(f"[ok] Git hook installed: {hook_path}")
